name: uri_template
version: 0.4.0
author: Dart Authors <misc@dartlang.org>
description: An implementation of  RFC 6570 URI Templates
homepage: https://github.com/dart-lang/uri_template
dependencies:
  quiver: '>=0.12.0'
dev_dependencies:
  unittest: any
